[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "lemonpie-cli"
dynamic = ["version"]
description = "LemonPie — A lightweight Ollama client for terminal users"
authors = [
  { name = "famousStratum", email = "info@versicode.com" }
]
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.11"

dependencies = [
  "ollama",
  "httpx",
  "platformdirs"
]

[project.urls]
homepage = "https://versicode.com/lemonpie"
repository = "https://github.com/famousStratum/LemonPie"
issues = "https://github.com/famousStratum/LemonPie/issues"

[project.scripts]
lm = "lemonpie.main:main"
lemonpie = "lemonpie.main:main"
lmConfig = "lemonpie.cli.config_cmd:main"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "src/lemonpie/_version.py"

[tool.hatch.build.targets.wheel]
packages = ["src/lemonpie"]
